scripts/install.sh: fail more gracefully when `curl` fails to download ollama.
previously, `curl` would download the assets and pipe it directly into `tar`.
while effective, the bourne shell does not have a `pipefail` option, so if
`curl` fails to download for some reason, `tar` continues to try to unpack an
incomplete tarball, resulting in this:

```text
+ status Downloading Linux arm64 bundle
+ echo >>> Downloading Linux arm64 bundle
>>> Downloading Linux arm64 bundle
+ curl --fail --show-error --location --progress-bar https://ollama.com/download/ollama-linux-arm64.tgz
+ sudo tar -xzf - -C /usr/local

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
+ cleanup
+ rm -rf /tmp/tmp.gumWtEeeSU
```

the new behavior now fails more gracefully:

```text
+ status Downloading Linux arm64 bundle
+ echo >>> Downloading Linux arm64 bundle
>>> Downloading Linux arm64 bundle
+ curl --fail --show-error --location --progress-bar --output ollama-linux-arm64.tgz https://ollama.com/download/ollama-linux-arm64.tgz

+ error Failed to download or extract Ollama
+ echo ERROR: Failed to download or extract Ollama
ERROR: Failed to download or extract Ollama
+ exit 1
+ cleanup
+ rm -rf /tmp/tmp.X3whvVjiUc
```

assuming the intent was to not leave assets behind by piping direct into `tar`,
this is a more POSIX-compliant way to handle the situation when a piped command
fails.  it will remove the tarball after unpacking.

Signed-off-by: Jacob Salmela <me@jacobsalmela.com>