llama/llama-mmap: fix missing include
Proper memory and vector headers (like in GCC 15.1) do not provide a the
uint32_t include, so cstdint is required.

llama-mmap.h:55:20: error: ‘uint32_t’ has not been declared
55 |     void write_u32(uint32_t val) const;